# https://registry.suse.com/
FROM registry.suse.com/bci/bci-base:latest

# packages
ENV ZYPPERCMD="zypper --non-interactive"
RUN $ZYPPERCMD install python3 python3-pip
RUN $ZYPPERCMD clean --all 

# python virtual env
ENV VIRTENV=/app/venv
RUN python3 -m venv ${VIRTENV}
RUN ${VIRTENV}/bin/pip install jupyterlab

# jupyterlab default port
EXPOSE 8888 

# set up an entrypoint to allow exec of jupyter as non-root user in the container
WORKDIR /app
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh
ENTRYPOINT ["/app/entrypoint.sh"]

# this is consumed by the entrypoint script
CMD ["/app/venv/bin/jupyter", "lab","--no-browser", "--ip=0.0.0.0", "--port=8888"]
