# https://registry.suse.com/
FROM registry.suse.com/bci/bci-base:latest

ENV ZYPPERCMD="zypper --non-interactive"

RUN $ZYPPERCMD install python3 python3-pip
RUN $ZYPPERCMD clean --all 
RUN pip install jupyterlab

EXPOSE 8888 
CMD ["jupyter", "lab", "--allow-root", "--no-browser", "--ip=0.0.0.0", "--port=8888"]
