# https://registry.suse.com/
FROM registry.suse.com/bci/bci-base:latest

ENV ZYPPERCMD="zypper --non-interactive"

RUN $ZYPPERCMD install python3 python3-pip
RUN $ZYPPERCMD clean --all

RUN python3 -m venv /home/virtenv

COPY requirements.txt .
RUN . /home/virtenv/bin/activate && pip install --upgrade pip
RUN . /home/virtenv/bin/activate && pip install -r requirements.txt 

# jupyter web port
EXPOSE 8888/tcp 

# https://denibertovic.com/posts/handling-permissions-with-docker-volumes/
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD [".", "/home/virtenv/bin/activate", "&&", "jupyter", "lab"]
