apiVersion: v1
kind: Service
metadata:
  name: {{ include "bci-jupyterhub-helm.fullname" . }}
  labels:
    {{- include "bci-jupyterhub-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "bci-jupyterhub-helm.selectorLabels" . | nindent 4 }}
