services:
  postgres:
    image: dp.apps.rancher.io/containers/postgresql:18.0
    container_name: mlflow_db
    restart: always
    environment:
      - POSTGRES_USER=mlflow
      - POSTGRES_PASSWORD=mlflow
      - POSTGRES_DB=mlflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mlflow:
    image: dp.apps.rancher.io/containers/mlflow:3.5.0
    container_name: mlflow_server
    restart: always
    command: >
      sh -c "
      pip install psycopg2-binary &&
      mlflow server
      --backend-store-uri postgresql://mlflow:mlflow@postgres:5432/mlflow
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
      "
    ports:
      - "5001:5000"
    volumes:
      - mlflow_artifacts:/mlflow/artifacts
    depends_on:
      - postgres

volumes:
  postgres_data:
  mlflow_artifacts:
