FROM registry.suse.com/bci/bci-base:15.7
ENV ZYPPERCMD="zypper --non-interactive"

# update packages
RUN $ZYPPERCMD update

# requirements 
RUN $ZYPPERCMD install python3 python3-devel wget awk
RUN $ZYPPERCMD clean --all

WORKDIR /build

# build
COPY --chmod=0700 install-miniconda.sh ./
COPY --chmod=0700 install-vllm.sh ./
RUN sh install-miniconda.sh
RUN sh install-vllm.sh

# optional vllm serve script
COPY --chmod=0700 vllm-serve.sh /usr/local/bin/
