# settings

unset -v BUILD_SHARED_SETTINGS

export BUILD_SRC_PREFIX=$HOME
export BUILD_INSTALL_PREFIX=/opt/openvino

export BUILD_FFMPEG_RELEASE="release/4.4"
export BUILD_OPENCV_RELEASE="4.12.0"
export BUILD_OPENVINO_RELEASE="releases/2025/3"
export BUILD_ONEAPI_RELEASE="2025.2"
export BUILD_PYTHON_VENV="$BUILD_SRC_PREFIX/openvino-venv"

export PATH=$INSTALL_PREFIX/bin:$PATH
export LD_LIBRARY_PATH=$INSTALL_PREFIX/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=$INSTALL_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH
export C_INCLUDE_PATH=$INSTALL_PREFIX/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$INSTALL_PREFIX/include:$CPLUS_INCLUDE_PATH
export PYTHONPATH=$INSTALL_PREFIX/python:$PYTHONPATH
export MANPATH=$INSTALL_PREFIX/share/man:$MANPATH

export BUILD_SHARED_SETTINGS=1