#
# Install Intel oneAPI Base Toolkit with MKL on SUSE SLE BCI
#
# https://www.intel.com/content/www/us/en/developer/tools/oneapi/toolkits.html#base-kit

# https://registry.suse.com/
FROM registry.suse.com/bci/bci-base:15.7

ENV ZYPPERCMD="zypper --non-interactive"

# update packages
RUN $ZYPPERCMD update

RUN $ZYPPERCMD addrepo https://yum.repos.intel.com/oneapi oneAPI
RUN rpm --import https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB

# prerequisites for oneAPI
RUN $ZYPPERCMD install -t pattern devel_basis
# prerequisites for /opt/intel/oneapi/setvars.sh
RUN $ZYPPERCMD install awk ps

# install oneAPI
RUN $ZYPPERCMD install intel-oneapi-base-toolkit intel-oneapi-mkl
RUN $ZYPPERCMD clean -a
